apiVersion: v1
kind: Service
metadata:
  name: inference
  labels:
    app.kubernetes.io/name: inference
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: inference
  ports:
    - name: http
      port: 8083
      targetPort: http
