apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sitewatch
spec:
  ingressClassName: nginx
  rules:
    - host: sitewatch.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  name: http
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  name: http
          - path: /docs
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  name: http
          - path: /api-doc
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  name: http
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  name: http

