apiVersion: v1
kind: Secret
metadata:
  name: sitewatch-secrets
type: Opaque
stringData:
  DATABASE_URL: REPLACE_ME
  REDIS_URL: REPLACE_ME
  NATS_URL: REPLACE_ME
  S3_ENDPOINT: REPLACE_ME
  S3_ACCESS_KEY: REPLACE_ME
  S3_SECRET_KEY: REPLACE_ME

