/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check whether the API process is alive */
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check required infrastructure dependencies */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta/equipment-classes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List stable equipment class codes */
        get: operations["listEquipmentClasses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a short-lived S3 upload URL */
        post: operations["createUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/observations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue an uploaded image for analysis */
        post: operations["createObservation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/observations/{observationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read processing state and detections */
        get: operations["getObservation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/stages:import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate and import a normalized project schedule */
        post: operations["importWorkStages"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/deviations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List evidence-backed deviations for a project */
        get: operations["listDeviations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            status: components["schemas"]["ServiceStatus"];
            service: string;
            version: string;
            /** Format: date-time */
            timestamp: string;
        };
        ReadinessResponse: {
            status: components["schemas"]["ServiceStatus"];
            dependencies: components["schemas"]["DependencyStatus"][];
            /** Format: date-time */
            timestamp: string;
        };
        /** @enum {string} */
        ServiceStatus: "up" | "degraded" | "down";
        DependencyStatus: {
            name: string;
            status: components["schemas"]["ServiceStatus"];
            /** Format: int64 */
            latency_ms: number;
            detail?: string;
        };
        /** @enum {string} */
        EquipmentClass: "dump_truck" | "excavator" | "road_roller" | "loader_crane" | "concrete_mixer" | "bulldozer" | "truck" | "mobile_crane" | "tower_crane" | "piling_rig";
        EquipmentClassMetadata: {
            code: components["schemas"]["EquipmentClass"];
            title_ru: string;
        };
        CreateUploadRequest: {
            filename: string;
            /** @enum {string} */
            media_type: "image/jpeg" | "image/png" | "image/webp";
            /** Format: int64 */
            size_bytes: number;
            sha256: string;
        };
        CreateUploadResponse: {
            /** Format: uuid */
            asset_id: string;
            object_key: string;
            /** Format: uri */
            upload_url: string;
            required_headers: {
                [key: string]: string;
            };
            /** Format: date-time */
            expires_at: string;
        };
        AssetRef: {
            object_key: string;
            sha256: string;
            /** @enum {string} */
            media_type: "image/jpeg" | "image/png" | "image/webp";
            /** Format: int64 */
            size_bytes: number;
            width_px: number;
            height_px: number;
        };
        CreateObservationRequest: {
            /** Format: uuid */
            project_id: string;
            /** Format: uuid */
            camera_id: string;
            /** Format: uuid */
            zone_id: string;
            /** Format: date-time */
            captured_at: string;
            /** @enum {string} */
            source: "upload" | "camera_snapshot" | "rtsp_frame" | "synthetic";
            asset: components["schemas"]["AssetRef"];
        };
        ObservationAcceptedResponse: {
            /** Format: uuid */
            observation_id: string;
            /** Format: uuid */
            job_id: string;
            /** @constant */
            status: "queued";
            /** Format: date-time */
            queued_at: string;
            /** Format: uuid */
            correlation_id: string;
        };
        Observation: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            project_id: string;
            /** Format: uuid */
            camera_id: string;
            /** Format: uuid */
            zone_id: string;
            /** Format: date-time */
            captured_at: string;
            /** @enum {string} */
            status: "queued" | "processing" | "analyzed" | "rejected";
            asset: components["schemas"]["AssetRef"];
            detections: components["schemas"]["Detection"][];
            /** Format: date-time */
            analyzed_at?: string;
            rejection_reason?: string;
        };
        Detection: {
            /** Format: uuid */
            id: string;
            equipment_class: components["schemas"]["EquipmentClass"];
            confidence: number;
            bounding_box: components["schemas"]["BoundingBox"];
            model_version: string;
        };
        BoundingBox: {
            x_min: number;
            y_min: number;
            x_max: number;
            y_max: number;
        };
        WorkStageImport: {
            timezone: string;
            source: string;
            stages: components["schemas"]["WorkStageInput"][];
        };
        WorkStageInput: {
            code: string;
            parent_code?: string | null;
            name: string;
            zone_code: string;
            /** Format: date-time */
            planned_start: string;
            /** Format: date-time */
            planned_end: string;
            observable_from_camera: boolean;
            equipment_rules: components["schemas"]["EquipmentRule"][];
        };
        EquipmentRule: {
            equipment_class: components["schemas"]["EquipmentClass"];
            /** @enum {string} */
            expectation: "required" | "optional" | "unexpected";
            min_count: number;
            max_count?: number | null;
            min_confidence: number;
            persistence_frames: number;
        };
        ImportAcceptedResponse: {
            /** Format: uuid */
            job_id: string;
            /** @constant */
            status: "queued";
            /** Format: date-time */
            accepted_at: string;
        };
        DeviationPage: {
            items: components["schemas"]["Deviation"][];
            next_cursor?: string | null;
        };
        Deviation: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            project_id: string;
            /** Format: uuid */
            stage_id: string;
            /** Format: uuid */
            zone_id: string;
            /** @enum {string} */
            kind: "missing_required_equipment" | "unexpected_equipment" | "count_outside_range" | "insufficient_evidence" | "schedule_conflict";
            /** @enum {string} */
            severity: "info" | "warning" | "critical";
            /** @enum {string} */
            status: "open" | "acknowledged" | "resolved" | "dismissed";
            title: string;
            explanation: string;
            expected: components["schemas"]["EquipmentCount"][];
            observed: components["schemas"]["EquipmentCount"][];
            evidence_observation_ids: string[];
            /** Format: date-time */
            detected_at: string;
        };
        EquipmentCount: {
            equipment_class: components["schemas"]["EquipmentClass"];
            count: number;
        };
        ProblemDetails: {
            /** Format: uri-reference */
            type: string;
            title: string;
            status: number;
            detail: string;
            instance: string;
            trace_id: string;
            errors: components["schemas"]["FieldViolation"][];
        };
        FieldViolation: {
            field: string;
            message: string;
        };
    };
    responses: {
        /** @description Malformed request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Missing or invalid access token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Request is syntactically valid but violates domain constraints */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        /** @description UUID generated once by the caller and reused for safe retries */
        IdempotencyKey: string;
        ProjectId: string;
        ObservationId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API is ready to receive traffic */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description A required dependency is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    listEquipmentClasses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Supported detector and rule-engine taxonomy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipmentClassMetadata"][];
                };
            };
        };
    };
    createUpload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUploadRequest"];
            };
        };
        responses: {
            /** @description Upload slot created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateUploadResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    createObservation: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID generated once by the caller and reused for safe retries */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateObservationRequest"];
            };
        };
        responses: {
            /** @description Observation accepted for asynchronous processing */
            202: {
                headers: {
                    /** @description URL of the observation resource */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservationAcceptedResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description The idempotency key was reused with a different request */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    getObservation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                observationId: components["parameters"]["ObservationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Observation found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Observation"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    importWorkStages: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID generated once by the caller and reused for safe retries */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkStageImport"];
            };
        };
        responses: {
            /** @description Schedule accepted for validation and import */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportAcceptedResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    listDeviations: {
        parameters: {
            query?: {
                status?: "open" | "acknowledged" | "resolved" | "dismissed";
                severity?: "info" | "warning" | "critical";
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of deviations sorted by latest evidence */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviationPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
}
