[package]
name = "sitewatch-schedule"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
async-nats.workspace = true
axum.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
sitewatch-contracts = { path = "../../crates/contracts" }
sitewatch-domain = { path = "../../crates/domain" }
sqlx.workspace = true
subtle = "2.6.1"
tokio.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true

[lints]
workspace = true
