apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: api-replicas.yaml
  - path: web-replicas.yaml
images:
  - name: ghcr.io/sitewatch/api
    newName: sitewatch-api
    newTag: dev
  - name: ghcr.io/sitewatch/web
    newName: sitewatch-web
    newTag: dev
